# 1. Write a Python Program to Add Two Matrices?

In [3]:
import numpy as np

mat1 = np.array([[11,14,26],
        [17,57,8],
        [18,12,13]])
mat2 = np.array([[12,43,74],
        [5,8,3],
        [8,9,9]])

matsum = np.add(mat1,mat2)


In [4]:
matsum

array([[ 23,  57, 100],
       [ 22,  65,  11],
       [ 26,  21,  22]])

# 2. Write a Python Program to Multiply Two Matrices?

In [5]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)


In [6]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [7]:
x2

array([0., 1., 2.])

In [17]:
r = np.dot(x1 , x2)

In [18]:
r.shape

(3,)

In [19]:
x1.shape

(3, 3)

In [20]:
x2.shape

(3,)

In [21]:
r

array([ 5., 14., 23.])

# 3. Write a Python Program to Transpose a Matrix?

In [25]:
X = [[12,7,4],
    [4 ,5,67],
    [3 ,8,50]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

 
for i in range(len(X)):
    for j in range(len(X[0])):
        result[j][i] = X[i][j]

for r in result:
    print(r)

[12, 4, 3]
[7, 5, 8]
[4, 67, 50]


# 4.Write a Python Program to Sort Words in Alphabetic Order?

In [28]:
str_sort = "I am doing fullstack from ineuron"
words = [word.lower() for word in str_sort.split()]
words.sort()
for word in words:
    print(word)

am
doing
from
fullstack
i
ineuron


# 5. Write a Python Program to Remove Punctuation From a String?

In [34]:
puc = [".",",",";",":","?","-","!","_","...","'"]
in_str = input("Please enter the string ")

Please enter the string India is my country. Do you love your country? It's beautiful. How are you?? it's good!!!!!!. a_b


In [35]:
ch1 = [ch for ch in in_str if ch not in puc]

In [36]:
''.join(ch1)

'India is my country Do you love your country Its beautiful How are you its good ab'